# config/role_addresses.yml

default: &default
  # локальна частина, яка вважається службовою (без +tag, без лапок, нижній регістр)
  local_parts:
    # === Generic / catch-all ===
    - admin
    - administrator
    - admins
    - root
    - system
    - sys
    - sysadmin
    - noreply
    - no-reply
    - do-not-reply
    - donotreply
    - robot
    - bot
    - auto
    - auto-reply
    - autoreply
    - noanswer
    - office
    - info
    - contact
    - hello
    - team
    - staff
    - employees
    - reception
    - receptiondesk
    - frontdesk
    - help
    - support
    - helpdesk
    - servicedesk
    - service-desk
    - services
    - csr
    - care
    - customercare
    - customer-care
    - customerservice
    - customer-service
    - hotline
    - callcenter
    - call-centre
    - call-centre-ua
    - callback
    - feedback
    - mail
    - mailbox
    - post
    - newsletter
    - news
    - press
    - pr
    - pressroom
    - media
    - announcements
  
    # === Web / RFC 2142 standard mailboxes ===
    - webmaster
    - postmaster
    - hostmaster
    - abuse
    - security
    - noc
    - dns
    - www
    - www-data
    - ftp
    - smtp
    - ssl
    - tls
    - dmarc
    - postmaster
    - hostmaster
  
    # === IT / Engineering / DevOps ===
    - it
    - it-support
    - itdesk
    - ithelpdesk
    - support-it
    - ops
    - devops
    - sre
    - qa
    - test
    - testing
    - staging
    - ci
    - cd
    - git
    - scm
    - svn
    - jira
    - confluence
    - bitbucket
    - github
    - gitlab
    - bugs
    - bugreport
    - bug-reports
    - issues
    - tickets
    - ticket
    - infra
    - infrastructure
    - network
    - netadmin
  
    # === Sales / Commercial ===
    - sales
    - sale
    - b2b
    - b2c
    - commerce
    - commercial
    - bizdev
    - business
    - partnerships
    - partner
    - partners
    - dealers
    - dealer
    - resellers
    - reseller
    - distribution
    - distributor
    - distributors
    - franchise
    - franchisee
    - wholesale
    - retail
    - shop
    - store
    - stores
    - showroom
    - pointofsale
    - pos
  
    # === Orders / Customer Ops ===
    - order
    - orders
    - track
    - tracking
    - shipment
    - shipping
    - delivery
    - deliveries
    - logistics
    - fulfilment
    - fulfillment
    - warehouse
    - stock
    - inventory
    - returns
    - rma
    - exchange
    - warranty
    - guarantees
    - guarantee
    - claim
    - claims
    - complaints
  
    # === Procurement / Supply Chain ===
    - procurement
    - purchasing
    - purchase
    - purchases
    - supply
    - supplies
    - supplier
    - suppliers
    - sourcing
    - tenders
    - tender
    - rfq
    - rfp
    - rfi
    - bids
    - bidding
    - contract
    - contracts
  
    # === Finance / Billing / Accounting ===
    - finance
    - finances
    - billing
    - bill
    - invoice
    - invoices
    - invoicing
    - accounts
    - accounting
    - ar
    - ap
    - treasury
    - payments
    - payment
    - payables
    - receivables
    - cashback
    - refunds
    - refund
    - taxes
    - tax
    - vat
    - buk
    - buh
    - buch
    - buchhalter
    - buhgalter
    - buhgalteria
  
    # === HR / Hiring ===
    - hr
    - people
    - talent
    - recruiting
    - recruitment
    - hire
    - hiring
    - jobs
    - job
    - careers
    - career
    - cv
    - resume
    - resumes
    - internships
    - intern
    - interns
    - onboarding
    - offboarding
    - payroll
    - benefits
  
    # === Marketing / Growth ===
    - marketing
    - market
    - growth
    - performance
    - acquisition
    - retention
    - lifecycle
    - crm
    - brand
    - branding
    - creative
    - design
    - designers
    - marcom
    - communications
    - comms
    - social
    - smm
    - community
    - events
    - event
    - sponsorships
    - promo
    - promotions
    - affiliates
    - affiliate
  
    # === Legal / Compliance / Privacy ===
    - legal
    - compliance
    - privacy
    - gdpr
    - dpo
    - dataprotection
    - data-protection
    - terms
    - policy
    - policies
    - ethics
    - audit
    - risk
    - whistleblower
  
    # === Executive / Admin ===
    - ceo
    - coo
    - cto
    - cfo
    - cmo
    - cro
    - cio
    - ciso
    - board
    - directors
    - secretary
    - pa
    - assistant
    - assistants
    - office-manager
    - officemanager
    - admin-office
  
    # === Facilities / Operations ===
    - facilities
    - facility
    - operations
    - ops-team
    - maintenance
    - service
    - services
    - repair
    - repairs
    - support-center
    - support-centre
  
    # === Education / Info ===
    - info-ua
    - info-uk
    - info-en
    - support-ua
    - support-ru
    - support-en
  
    # === UA/RU transliterations (common in region) ===
    - zakaz
    - zakazy
    - orders-ua
    - zamovlennya
    - zamovlennja
    - zamovlennia
    - prodazhi
    - prodazh
    - prodaji
    - prodaz
    - pidtrymka
    - pidtrimka
    - dopomoga
    - dopomoha
    - dop
    - zapyt
    - zapit
    - zapros
    - remont
    - servis
    - service-ua
    - sklad
    - postavki
    - postavka
    - zakupki
    - zakupki
    - zakupivli
    - zakupivlya
    - zakup
    - oplata
    - platezh
    - platezhi
    - oplaty
    - rahunok
    - schet
    - scheta
    - buh
    - buhgalter
    - buhgalteria
    - garan 
    - garantia
    - garanitiya
    - dostavka
    - logistika
    - logistyka
    - reklamatsiya
    - reklamacija
  
    # === Security / Trust ===
    - trust
    - secops
    - security-team
    - securitydesk
    - cert
    - csirt
    - psirt
    - privacy-team
    - compliance-team
    - trustandsafety
    - safety
  
    # === Misc / Common project mailboxes ===
    - project
    - projects
    - roadmap
    - product
    - products
    - product-team
    - roadmap
    - office-kyiv
    - office-lviv
    - office-odessa
    - office-kharkiv
    - office-dnipro
    
    
    # === old name for deleted ===
    - abuse
    - admin
    - administrator
    - admissions
    - alerts
    - alumni
    - billing
    - book
    - bookings
    - boss
    - careers
    - contact
    - crm
    - dev
    - developer
    - developers
    - dns
    - domain
    - donotreply
    - events
    - feedback
    - finance
    - founder
    - founders
    - ftp
    - guest
    - help
    - hello
    - hostmaster
    - hr
    - info
    - invoicing
    - jobs
    - legal
    - mail
    - mailer
    - mailing
    - marketing
    - news
    - newsletter
    - newsletters
    - noreply
    - notifications
    - office
    - orders
    - owner
    - payment
    - payments
    - payroll
    - postmaster
    - press
    - pr
    - prod
    - product
    - products
    - receipts
    - register
    - registration
    - sales
    - security
    - service
    - services
    - shop
    - smtp
    - staff
    - support
    - sysadmin
    - team
    - teams
    - tech
    - test
    - testing
    - webmaster

  # регулярні вирази (рядками) для “схожих” службових локалів
  patterns:
    - '\bnore?ply\b'                   # noreply / no-reply
    - '\b(no|do)\.?not\.?reply\b'      # do.not.reply / donotreply
    - '\b(info|support|admin|sales|help|office)\b'
    - '\b(marketing|newsletter|newsletters?)\b'
    - '\b(postmaster|webmaster|hostmaster|abuse|security)\b'

  # домени з “крапка-неважлива” локальною частиною (gmail-логіка)
  dot_insensitive_domains:
    - gmail.com
    - googlemail.com

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default




